language: python
services:
  - docker
python:
  - '3.6'
script:
  - 'docker build -t ${TRAVIS_REPO_SLUG} .'
  - 'docker tag ${TRAVIS_REPO_SLUG} auth'
  - 'docker build -t dredd-auth . -f ./tests/Dockerfile'
  - 'cd tests'
  - 'docker-compose up -d auth-redis postgres'
  - 'docker-compose up auth'
after_success:
  - travis/publish.sh
